channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - defaults
dependencies:
  - cryptography
  - faker
  - pandas
  - pip
  - regex
  - snowflake-snowpark-python[pandas]
  - streamlit
  - xlrd
  - pmdarima
  - scikit-learn
  - croniter
  - pip:
    - snowflake-ingest
