channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - defaults
dependencies:
  - cryptography
  - faker
  - pandas
  - pip
  - regex
  - snowflake-snowpark-python[pandas]
  - streamlit
  - xlrd
  - pip:
    - snowflake-ingest
